config/routes.rb
Rails.application.routes.draw do

    root "supports#index"
    resources :supports

    get 'supports/:id/mark_resolved' => 'supports#mark_resolved'
    get 'supports/:id/mark_unresolved' => 'supports#mark_unresolved'

end

app/models/support.rb
class Support < ActiveRecord::Base
  validates :name, :email, :department, :message, presence: true

  self.per_page = 5

def self.search(search)
  if search
    where(['name LIKE ? OR email LIKE ? OR message LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"]).order("status ASC")
  else
    all.order("status ASC")
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  before_action :get_ticket, only: [:edit, :update, :destroy, :mark_resolved, :mark_unresolved]

  def index
    @supports = Support.paginate(:page => params[:page]).search(params[:search])
  end

  def new
    @support = Support.new
  end

  def create
    @support = Support.new(support_params)
    if @support.save
      redirect_to supports_path, notice: "Ticket created! Thank you for contacting us."
    else
      flash.now[:alert] = "Something went wrong when creating your ticket!"
      render :new
    end
  end

  def edit
  end

  def update
    if @support.update_attributes(support_params)
      redirect_to supports_path, notice: "Ticket is updated."
    else
      flash.now[:alert] = "Something went wrong when updating your request!"
      render :edit
    end
  end

  def destroy
    @support.destroy
    redirect_to supports_path, notice: "Ticket successfully destroyed."
  end

  def mark_resolved
    @support.status = 1
    @support.save
    redirect_to supports_path
  end

  def mark_unresolved
    @support.status = 0
    @support.save
    redirect_to supports_path
  end

  private


  def get_ticket
    @support = Support.find(params[:id])
  end

  def support_params
    params.require(:support).permit(:name, :email, :department, :message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Support Request</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="page-header">
    <div class="container-fluid">
      <nav>
        <%= link_to "Request List", supports_path %>
      </nav>
    </div>
  </header>

<div class="container">
  <% if flash[:notice] %>
    <div class = "alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class = "alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>
  
  <%= yield %>
</div>

</body>
</html>

app/views/supports/_form.html.erb
<% if @support.errors.any? %>
  <ul>
    <% @support.errors.full_messages.each do |err| %>
      <li><%= err %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @support do |f| %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :department %> : 
  <%= f.radio_button(:department, "Sales") %>
  <%= f.label(:sales, "Sales") %>
  <%= f.radio_button(:department, "Marketing") %>
  <%= f.label(:marketing, "Marketing") %>
  <%= f.radio_button(:department, "Technical") %>
  <%= f.label(:technical, "Technical") %>
</div>

<div class="form-group">
  <%= f.label :message %>
  <%= f.text_area :message, class: "form-control" %>
</div>

<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/supports/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

app/views/supports/index.html.erb
<h1>Support Requests</h1>

<div class="row getaway">
  <%= link_to "Create Support Request", new_support_path, class: "btn btn-primary" %>
</div>

<div class="row getaway">
  <div class="col-xs-9 col-md-6 col-md-offset-3">
    <%= form_tag supports_path, method: 'get' do %>
    <%= text_field_tag :search, params[:search], class: "form-control" %>
  </div>
  <div class="col-xs-3 col-md-3">
      <%= submit_tag "Search", name: nil, class: "btn btn-info" %>
    <% end %>
  </div>
</div>

<div class="row getaway">

  <div class="col-md-offset-2 col-md-8 col-xs-12">

    <table class="table table-striped table-bordered table-hover">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Department</th>
        <th>Message</th>
        <th>Actions</th>
      </tr>

      <% @supports.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= mail_to ticket.email %></td>
        <td><%= ticket.department %></td>
        <td><%= ticket.message %></td>
        <td>
            <%= link_to "Edit", edit_support_path(ticket), class: "btn btn-info" %> 
            <%= link_to "Delete", ticket, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %> 
            <% if ticket.status == 0 %>
              <%= link_to "Unresolved", { action: "mark_resolved", id: ticket.id }, data: { confirm: "Mark ticket resolved?"}, class: "btn btn-default" %>
            <% else %>
              <%= link_to "Resolved", { action: "mark_unresolved", id: ticket.id }, data: { confirm: "Mark ticket unresolved?"}, class: "btn btn-success" %>
            <% end %>
        </td>
      </tr>
      <% end %>
    </table>

    <div class="col-md-offset-4 col-md-4 col-xs-offset-4 col-xs-6">
      <%= will_paginate @supports %>
    </div>

  </div> <!--- colspan div -->

</div> <!--- row div -->

app/views/supports/new.html.erb
<h1>Create Request</h1>

<%= render 'form' %>